<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-04-23 09:52
=======
# Generated by Django 4.1.7 on 2023-04-23 09:47
>>>>>>> main

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
