# Generated by Django 4.2 on 2023-04-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='about',
            field=models.CharField(max_length=2000),
        ),
    ]
