# Generated by Django 4.2 on 2023-04-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_artist_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_id',
            new_name='artists',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='genre_id',
            new_name='genres',
        ),
    ]
