# Generated by Django 4.2 on 2023-04-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_listenhistory_song_listenhistory_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listenhistory',
            old_name='listen_date',
            new_name='stream_date',
        ),
    ]
