# Generated by Django 4.2 on 2023-04-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_release_day_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='cover_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
