# Generated by Django 4.1.7 on 2023-04-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_release_day_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='link',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='song',
            name='audio_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
