# Generated by Django 4.2 on 2023-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_rename_listen_date_listenhistory_stream_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
