# Generated by Django 4.1.7 on 2023-04-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_playlist_owner_delete_user'),
        ('music', '0005_remove_song_link_song_audio_file_song_audio_link_and_more'),
    ]

    operations = [
    ]
