# Generated by Django 4.2 on 2023-05-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_album_cover_path_alter_song_cover_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cover_path',
            field=models.ImageField(blank=True, null=True, upload_to='song_cover/'),
        ),
    ]
