# Generated by Django 4.2 on 2023-04-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_cover_path_song_cover_path'),
        ('music', '0006_merge_20230423_1830'),
    ]

    operations = [
    ]
