# Generated by Django 4.2 on 2023-04-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_merge_20230423_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
    ]
