# Generated by Django 4.1.7 on 2023-05-13 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_playlist_song_list_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
